name: Daily VTuber Update

# 毎日午前0時（UTC）に実行 → 日本時間 9:00 頃
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # ① リポジトリをチェックアウト
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # GITHUB_TOKEN で push できるように

      # ② Node.js セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ③ .env.local にシークレットを書き込む
      - name: Create env file
        run: echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" > .env.local

      # ④ 依存関係をインストール
      - name: Install dependencies
        run: npm ci

      # ⑤ スクリプトで channels.json を生成
      - name: Generate channels.json
        run: node scripts/updateChannels.js

      # ⑥ 生成されたファイルをコミット＆プッシュ
      - name: Commit and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/channels.json
          git commit -m 'chore: auto-update channels.json'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
