name: Daily VTuber Update

on:
  schedule:
    - cron: '0 0 * * *'       # 毎日00:00 UTC（日本時間9:00頃）
  workflow_dispatch:          # ← これが “Run workflow” ボタンを出すトリガー

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create env file
        run: echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" > .env.local

      - name: Install dependencies
        run: npm ci

      - name: Generate channels.json
        run: node scripts/updateChannels.js

      - name: Commit and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/channels.json
          git commit -m 'chore: auto-update channels.json' || echo "no changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
